# Generated by Django 5.2 on 2025-04-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tour_category",
                    models.CharField(
                        choices=[
                            ("local", "По Узбекистану"),
                            ("world", "По всему миру"),
                        ],
                        max_length=255,
                        verbose_name="Тип тура",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("short_description", models.TextField(verbose_name="Описание")),
                ("full_description", models.TextField(verbose_name="Описание")),
                ("itinerary", models.CharField(max_length=255, verbose_name="Маршрут")),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Местоположение"),
                ),
                ("duration_days", models.IntegerField(verbose_name="Количество дней")),
                (
                    "duration_nights",
                    models.IntegerField(verbose_name="Количество ночей"),
                ),
                (
                    "people_count",
                    models.PositiveIntegerField(verbose_name="Количество людей"),
                ),
                ("main_image", models.ImageField(upload_to="tours/main_images/")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=50, verbose_name="Цена"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Выделенный"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Тур",
                "verbose_name_plural": "Туры",
            },
        ),
        migrations.CreateModel(
            name="TourProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(verbose_name="Номер дня")),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="tours.tours",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="TourGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gallery_image", models.ImageField(upload_to="tours/gallery/")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="tours.tours",
                    ),
                ),
            ],
        ),
    ]
