# Generated by Django 5.2 on 2025-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_tourcategory_alter_tours_tour_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tours",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="tours",
            name="full_description",
            field=models.TextField(verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="tours",
            name="main_image",
            field=models.ImageField(
                upload_to="tours/main_images/", verbose_name="Главная картинка"
            ),
        ),
        migrations.AlterField(
            model_name="tours",
            name="short_description",
            field=models.TextField(verbose_name="Короткое описание"),
        ),
    ]
