# Generated by Django 5.2 on 2025-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_tours_slug_alter_tours_full_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tours",
            name="price",
        ),
        migrations.AddField(
            model_name="tours",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/banner_images/",
                verbose_name="Баннерная картинка",
            ),
        ),
        migrations.AddField(
            model_name="tours",
            name="lists_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/lists_images/",
                verbose_name="Картинка для списка туров",
            ),
        ),
        migrations.AlterField(
            model_name="tours",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/main_images/",
                verbose_name="Главная картинка",
            ),
        ),
    ]
