# Generated by Django 5.2 on 2025-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0005_remove_tours_price_tours_banner_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tours",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
