# Generated by Django 5.2 on 2025-04-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0006_tours_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(
                upload_to="slider/", verbose_name="Картинка 1550x950"
            ),
        ),
        migrations.AlterField(
            model_name="tourgalleryimage",
            name="gallery_image",
            field=models.ImageField(
                upload_to="tours/gallery/", verbose_name="Картинка для галереи 1200x700"
            ),
        ),
        migrations.AlterField(
            model_name="tours",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/banner_images/",
                verbose_name="Баннерная картинка 1920X800",
            ),
        ),
        migrations.AlterField(
            model_name="tours",
            name="lists_page_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/lists_images/",
                verbose_name="Картинка для списка 365X305",
            ),
        ),
        migrations.AlterField(
            model_name="tours",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/main_images/",
                verbose_name="Главная картинка 1200X700",
            ),
        ),
    ]
