# Generated by Django 5.2 on 2025-04-27 19:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0007_alter_slider_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tours",
            name="full_description",
            field=ckeditor.fields.RichTextField(verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="tours",
            name="itinerary",
            field=ckeditor.fields.RichTextField(verbose_name="Маршрут"),
        ),
    ]
