# Generated by Django 5.2 on 2025-04-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0008_alter_tours_full_description_alter_tours_itinerary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tours",
            name="itinerary",
            field=models.CharField(max_length=255, verbose_name="Маршрут"),
        ),
    ]
