# Generated by Django 5.2 on 2025-04-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0009_alter_tours_itinerary"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "guest_number",
                    models.PositiveIntegerField(verbose_name="Количество людей"),
                ),
                ("arrival_date", models.DateField(verbose_name="Дата прибытия")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="tours.tours",
                        verbose_name="Тур",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование тура",
                "verbose_name_plural": "Бронирования туров",
            },
        ),
    ]
