# Generated by Django 5.2 on 2025-04-28 18:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0010_tourbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourprogram",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Описание"),
        ),
    ]
