# Generated by Django 5.2 on 2025-04-30 05:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0011_alter_tourprogram_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tours",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
