# Generated by Django 5.2 on 2025-04-30 05:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0012_alter_tours_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tours",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
