# Generated by Django 5.2 on 2025-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0013_alter_tours_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcategory",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tours/categories/",
                verbose_name="Home картинка",
            ),
        ),
    ]
