# Generated by Django 5.2 on 2025-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0014_tourcategory_featured_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("about_us", models.TextField(verbose_name="О нас")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=255, verbose_name="Телефон")),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_page/",
                        verbose_name="Картинка баннера 1920x800",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
        ),
    ]
