# Generated by Django 5.2 on 2025-05-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0015_contactpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactpage",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
    ]
