# Generated by Django 5.2 on 2025-05-01 18:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0016_alter_contactpage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourcategory",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание en"),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название en"
            ),
        ),
        migrations.AddField(
            model_name="tourcategory",
            name="slug_en",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг en"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="about_us",
            field=ckeditor.fields.RichTextField(verbose_name="О нас"),
        ),
    ]
