# Generated by Django 5.2 on 2025-05-01 19:54

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0017_tourcategory_description_en_tourcategory_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="about_us_en",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="О нас en"
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Заголовок en"
            ),
        ),
        migrations.AddField(
            model_name="tourprogram",
            name="description_en",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание en"
            ),
        ),
        migrations.AddField(
            model_name="tourprogram",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Заголовок en"
            ),
        ),
        migrations.AddField(
            model_name="tours",
            name="full_description_en",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Полное описание en"
            ),
        ),
        migrations.AddField(
            model_name="tours",
            name="itinerary_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Маршрут en"
            ),
        ),
        migrations.AddField(
            model_name="tours",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Местоположение en"
            ),
        ),
        migrations.AddField(
            model_name="tours",
            name="short_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Короткое описание en"
            ),
        ),
        migrations.AddField(
            model_name="tours",
            name="slug_en",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                null=True,
                populate_from="title_en",
                unique=True,
                verbose_name="Slug en",
            ),
        ),
        migrations.AddField(
            model_name="tours",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название en"
            ),
        ),
    ]
