# Generated by Django 5.2 on 2025-05-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0018_contactpage_about_us_en_contactpage_title_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactpage",
            options={
                "verbose_name": "Страница Контакты",
                "verbose_name_plural": "Страница Контакты",
            },
        ),
        migrations.AddField(
            model_name="contactpage",
            name="address_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес en"
            ),
        ),
    ]
