# Generated by Django 5.2 on 2025-05-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0019_alter_contactpage_options_contactpage_address_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="UzbekistanCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Название en"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                ("slug_en", models.SlugField(unique=True, verbose_name="Слаг en")),
                (
                    "image",
                    models.ImageField(
                        upload_to="uzbekistan/categories/", verbose_name="Картинка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория Узбекистана",
                "verbose_name_plural": "Категории Узбекистана",
            },
        ),
        migrations.CreateModel(
            name="Uzbekistan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("content_en", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uzbekistan/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="tours.uzbekistancategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Узбекистан",
                "verbose_name_plural": "Узбекистан",
            },
        ),
    ]
