# Generated by Django 5.2 on 2025-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0020_uzbekistancategory_uzbekistan"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzbekistan",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="uzbekistan",
            name="slug_en",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг en"
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistan",
            name="content",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="uzbekistan",
            name="content_en",
            field=models.TextField(verbose_name="Текст en"),
        ),
        migrations.AlterField(
            model_name="uzbekistan",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="uzbekistan",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Название en"
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancategory",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название en"
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancategory",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancategory",
            name="slug_en",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг en"
            ),
        ),
    ]
