# Generated by Django 5.2 on 2025-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0021_uzbekistan_slug_uzbekistan_slug_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UzbekistanCities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название en",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                (
                    "slug_en",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Слаг en"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="uzbekistan/cities/", verbose_name="Картинка"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "text_en",
                    models.TextField(blank=True, null=True, verbose_name="Текст en"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город Узбекистана",
                "verbose_name_plural": "Города Узбекистана",
            },
        ),
    ]
