# Generated by Django 5.2 on 2025-05-02 19:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0022_uzbekistancities"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzbekistancategory",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="uzbekistancategory",
            name="text_en",
            field=models.TextField(blank=True, null=True, verbose_name="Текст en"),
        ),
        migrations.AlterField(
            model_name="uzbekistan",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistan",
            name="slug_en",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="title_en",
                unique=True,
                verbose_name="Слаг en",
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancategory",
            name="slug_en",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="name_en",
                unique=True,
                verbose_name="Слаг en",
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancities",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancities",
            name="slug_en",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="name_en",
                unique=True,
                verbose_name="Слаг en",
            ),
        ),
    ]
