# Generated by Django 5.2 on 2025-05-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0023_uzbekistancategory_text_uzbekistancategory_text_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uzbekistancategory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uzbekistan/categories/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancities",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uzbekistan/cities/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="uzbekistancities",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
    ]
