# Generated by Django 5.2 on 2025-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0024_alter_uzbekistancategory_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uzbekistan",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Активный"
            ),
        ),
        migrations.AddField(
            model_name="uzbekistancategory",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Активный"
            ),
        ),
        migrations.AddField(
            model_name="uzbekistancities",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Активный"
            ),
        ),
    ]
